// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_hardware_revision_string         14
#define gattdb_firmware_revision_string         16
#define gattdb_serial_number_string            18
#define gattdb_door_lock                       21
#define gattdb_door_status                     24
#define gattdb_door_password                   27
#define gattdb_door_alarm_trigger_time         30
#define gattdb_door_alarm_status               32
#define gattdb_ota_control                     36
#define gattdb_battery_level                   39

#endif
