// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_appearance                      13
#define gattdb_peripheral_preferred_connection_parameters         15
#define gattdb_hardware_revision_string         18
#define gattdb_firmware_revision_string         20
#define gattdb_manufacturer_name_string         22
#define gattdb_serial_number_string            24
#define gattdb_door_lock                       27
#define gattdb_door_status                     30
#define gattdb_door_password                   33
#define gattdb_door_sensor_alarm_time          36
#define gattdb_door_auto_lock_time             38
#define gattdb_enable_auto_door_lock           40
#define gattdb_special_command                 42
#define gattdb_battery_level_cell              45
#define gattdb_battery_level_motor             48
#define gattdb_ota_control                     52

#endif
