// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_appearance                      13
#define gattdb_peripheral_preferred_connection_parameters         15
#define gattdb_hardware_revision_string         18
#define gattdb_firmware_revision_string         20
#define gattdb_serial_number_string            22
#define gattdb_door_lock                       25
#define gattdb_door_status                     28
#define gattdb_door_password                   31
#define gattdb_door_alarm_trigger_time         34
#define gattdb_door_alarm_status               36
#define gattdb_ota_control                     40
#define gattdb_battery_level                   43

#endif
